apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fixity

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

# Note: secret.yaml.template is NOT included in resources
# Secrets should be created separately using sealed-secrets or kubectl create secret
