apiVersion: v1
kind: Service
metadata:
  name: fixity-service
  namespace: fixity
  labels:
    app: fixity
spec:
  selector:
    app: fixity
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
